// Generates src/icons.ts from @phosphor-icons/core (dev-only).
// Extracts the inner path markup for the icons we map to node types, so the runtime
// package carries no icon dependency and diagrams stay self-contained.
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const regular = join(process.cwd(), "node_modules", "@phosphor-icons", "core", "assets", "regular");

// node type -> Phosphor icon name
const MAP = {
  ui: "app-window",
  client: "device-mobile",
  gateway: "plugs-connected",
  service: "cube",
  job: "timer",
  queue: "queue",
  cache: "lightning",
  datastore: "database",
  external: "cloud",
};

function innerPaths(svg) {
  // Drop the outer <svg ...> ... </svg> and the transparent sizing rect.
  let inner = svg.replace(/^[\s\S]*?<svg[^>]*>/, "").replace(/<\/svg>\s*$/, "");
  inner = inner.replace(/<rect[^>]*fill="none"[^>]*\/>/g, "");
  return inner.trim();
}

const entries = Object.entries(MAP).map(([type, name]) => {
  const svg = readFileSync(join(regular, `${name}.svg`), "utf8");
  return [type, innerPaths(svg)];
});

const body = entries
  .map(([type, paths]) => `  ${type}: ${JSON.stringify(paths)},`)
  .join("\n");

const out = `// AUTO-GENERATED by scripts/gen-icons.mjs from @phosphor-icons/core (regular weight, MIT).
// Do not edit by hand. Node-type -> inner SVG path markup (viewBox 0 0 256 256).
import type { NodeType } from "./schema.js";

export const NODE_ICON_PATHS: Record<NodeType, string> = {
${body}
};

/** Wrap icon paths in a self-contained inline SVG that inherits color via currentColor. */
export function iconSvg(type: NodeType, size = 20): string {
  const paths = NODE_ICON_PATHS[type] ?? NODE_ICON_PATHS.service;
  return \`<svg class="node-icon" width="\${size}" height="\${size}" viewBox="0 0 256 256" fill="currentColor" aria-hidden="true">\${paths}</svg>\`;
}
`;

writeFileSync("src/icons.ts", out);
console.log("Wrote src/icons.ts with icons:", Object.keys(MAP).join(", "));
